# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Chronicle < Formula
  desc "Ops-logs as a product: tenant event logs with declared indexes, on NATS"
  homepage "https://github.com/impire-io/chronicle"
  version "0.2.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/impire-io/chronicle/releases/download/v0.2.2/chronicle_0.2.2_darwin_amd64.tar.gz"
      sha256 "523a7e8bd3cc0f6cf65ed4fb5080168f47b622bd5bb56835e00c44a1fe68b7dd"

      define_method(:install) do
        bin.install "chronicle"
        bin.install "chronicle-node"
        bin.install "chronicle-workload"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/impire-io/chronicle/releases/download/v0.2.2/chronicle_0.2.2_darwin_arm64.tar.gz"
      sha256 "750603de7ed44cba115f69f64ff5a4fa4891ab7fae11df97c6901533d17a0406"

      define_method(:install) do
        bin.install "chronicle"
        bin.install "chronicle-node"
        bin.install "chronicle-workload"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/impire-io/chronicle/releases/download/v0.2.2/chronicle_0.2.2_linux_amd64.tar.gz"
      sha256 "774b4a404554b754b3d522fdb1800699a5343dd909e72ccb34c6e076bb1e4a0b"
      define_method(:install) do
        bin.install "chronicle"
        bin.install "chronicle-node"
        bin.install "chronicle-workload"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/impire-io/chronicle/releases/download/v0.2.2/chronicle_0.2.2_linux_arm64.tar.gz"
      sha256 "7fe95f8d8b78a6379d5a54faaed8b006dd89478f7d224a06ff23866140d69d1c"
      define_method(:install) do
        bin.install "chronicle"
        bin.install "chronicle-node"
        bin.install "chronicle-workload"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/chronicle version")
  end
end
