# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Chronicle < Formula
  desc "Ops-logs as a product: tenant event logs with declared indexes, on NATS"
  homepage "https://github.com/impire-io/chronicle"
  version "0.2.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/impire-io/chronicle/releases/download/v0.2.1/chronicle_0.2.1_darwin_amd64.tar.gz"
      sha256 "ef127f2ed03b01509f3944edaddb3d00e138d438434fc387fbbf592bd5551383"

      define_method(:install) do
        bin.install "chronicle"
        bin.install "chronicle-node"
        bin.install "chronicle-workload"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/impire-io/chronicle/releases/download/v0.2.1/chronicle_0.2.1_darwin_arm64.tar.gz"
      sha256 "409635c0930c8cf7edc5e7b4fd206b81b2814bf17e1fa2ade1c8893516b1bc3b"

      define_method(:install) do
        bin.install "chronicle"
        bin.install "chronicle-node"
        bin.install "chronicle-workload"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/impire-io/chronicle/releases/download/v0.2.1/chronicle_0.2.1_linux_amd64.tar.gz"
      sha256 "fa8deef414c481eba7c2f552ddb702eccfa0a730084e57d92700132ec7cbee6f"
      define_method(:install) do
        bin.install "chronicle"
        bin.install "chronicle-node"
        bin.install "chronicle-workload"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/impire-io/chronicle/releases/download/v0.2.1/chronicle_0.2.1_linux_arm64.tar.gz"
      sha256 "e39acc83b0b26a3f36eea3bd111606e6a592422588cd6ab70af973384c56385b"
      define_method(:install) do
        bin.install "chronicle"
        bin.install "chronicle-node"
        bin.install "chronicle-workload"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/chronicle version")
  end
end
