# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hits < Formula
  desc "Headless, agent-native issue tracking"
  homepage "https://github.com/impire-io/hits"
  version "0.1.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/impire-io/hits/releases/download/v0.1.1/hits_0.1.1_darwin_amd64.tar.gz"
      sha256 "4937381ecd0cb51d42c80e77d1372bd7186fc658fff2d4eaef0211d926a4c3c8"

      define_method(:install) do
        bin.install "hits"
        bin.install "hits-mcp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/impire-io/hits/releases/download/v0.1.1/hits_0.1.1_darwin_arm64.tar.gz"
      sha256 "b890a30c37fdedb60511150dc21c95fdd6c330cb516156e412ae9877238c31fa"

      define_method(:install) do
        bin.install "hits"
        bin.install "hits-mcp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/impire-io/hits/releases/download/v0.1.1/hits_0.1.1_linux_amd64.tar.gz"
      sha256 "dc733315954e6e016248a62a4560c9194c43f8329cdc8dc89decc550fcc66931"
      define_method(:install) do
        bin.install "hits"
        bin.install "hits-mcp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/impire-io/hits/releases/download/v0.1.1/hits_0.1.1_linux_arm64.tar.gz"
      sha256 "cba614488b299d19877ab13923c8e4fa11efa8537c401df37680057f030f3327"
      define_method(:install) do
        bin.install "hits"
        bin.install "hits-mcp"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/hits version")
  end
end
