# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hits < Formula
  desc "Headless, agent-native issue tracking"
  homepage "https://github.com/impire-io/hits"
  version "0.2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/impire-io/hits/releases/download/v0.2.0/hits_0.2.0_darwin_amd64.tar.gz"
      sha256 "d352663131d50d464ba7df0874d500d38f05b5130f8c8039537c29fd1d92ad51"

      define_method(:install) do
        bin.install "hits"
        bin.install "hits-mcp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/impire-io/hits/releases/download/v0.2.0/hits_0.2.0_darwin_arm64.tar.gz"
      sha256 "5d72de5bb2445e0f37dc69e7f3ebdb058aeebbc72cf0449050d9ce3135aa2628"

      define_method(:install) do
        bin.install "hits"
        bin.install "hits-mcp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/impire-io/hits/releases/download/v0.2.0/hits_0.2.0_linux_amd64.tar.gz"
      sha256 "8cc082d8c4a29f283aefd94ba0cf5cadff80d6fb98c0d191680e3cfaf7a569a5"
      define_method(:install) do
        bin.install "hits"
        bin.install "hits-mcp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/impire-io/hits/releases/download/v0.2.0/hits_0.2.0_linux_arm64.tar.gz"
      sha256 "abdd4a351b9ef7f43b137598b3b811ddeb4232b56cb2efbe9d0903de63f2023f"
      define_method(:install) do
        bin.install "hits"
        bin.install "hits-mcp"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/hits version")
  end
end
