# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Soulstream < Formula
  desc "Your realm in one binary — the Soulstream node"
  homepage "https://github.com/impire-io/soulstream"
  version "0.13.0-rc.12"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/impire-io/soulstream/releases/download/v0.13.0-rc.12/soulstream_0.13.0-rc.12_darwin_amd64.tar.gz"
      sha256 "04636e3b8674c7bb7afde83105fe8b8dd4f385cbfa06727989def87ea55a9182"

      define_method(:install) do
        bin.install "soulstream"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/impire-io/soulstream/releases/download/v0.13.0-rc.12/soulstream_0.13.0-rc.12_darwin_arm64.tar.gz"
      sha256 "75e695df2bdb1d7e09daf988cd5fe551d0d5efe0f093b096e7f051e7a55bc3e5"

      define_method(:install) do
        bin.install "soulstream"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/impire-io/soulstream/releases/download/v0.13.0-rc.12/soulstream_0.13.0-rc.12_linux_amd64.tar.gz"
      sha256 "c976e7c42bbfc85cde529d3a01d5680c0dbefb9f50b96625b8fe8ad5b37e4ff6"
      define_method(:install) do
        bin.install "soulstream"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/impire-io/soulstream/releases/download/v0.13.0-rc.12/soulstream_0.13.0-rc.12_linux_arm64.tar.gz"
      sha256 "5db574aeb2e61a02e35facf32e14faac4382acb85ff14ab7bc8f9cb094528894"
      define_method(:install) do
        bin.install "soulstream"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/soulstream version")
  end
end
