# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Soulstream < Formula
  desc "Your realm in one binary — the Soulstream node"
  homepage "https://github.com/impire-io/soulstream"
  version "0.14.0-rc.9"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/impire-io/soulstream/releases/download/v0.14.0-rc.9/soulstream_0.14.0-rc.9_darwin_amd64.tar.gz"
      sha256 "f266ad5bad30eb30bfec65ac2a18d264d366572e81aa1411c8b73792df15ae5e"

      define_method(:install) do
        bin.install "soulstream"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/impire-io/soulstream/releases/download/v0.14.0-rc.9/soulstream_0.14.0-rc.9_darwin_arm64.tar.gz"
      sha256 "6375a9f50ad377157622bee1000637c31d458722c57f0192318ac68891b35779"

      define_method(:install) do
        bin.install "soulstream"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/impire-io/soulstream/releases/download/v0.14.0-rc.9/soulstream_0.14.0-rc.9_linux_amd64.tar.gz"
      sha256 "5951681258373b97c91f32436da96d1970d137a0e55f8df6b601490aeab70f2e"
      define_method(:install) do
        bin.install "soulstream"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/impire-io/soulstream/releases/download/v0.14.0-rc.9/soulstream_0.14.0-rc.9_linux_arm64.tar.gz"
      sha256 "33ff1250160042c6b75d54b609d99c2d65cddd38d245d5b5dee16c2e0e90fa4d"
      define_method(:install) do
        bin.install "soulstream"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/soulstream version")
  end
end
