# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Soulstream < Formula
  desc "Your realm in one binary — the Soulstream node"
  homepage "https://github.com/impire-io/soulstream"
  version "0.14.0-rc.4"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/impire-io/soulstream/releases/download/v0.14.0-rc.4/soulstream_0.14.0-rc.4_darwin_amd64.tar.gz"
      sha256 "7e00115458c4207027e8ac98d827f3652605ef7ef0c7457d0a59862bfb8a5c93"

      define_method(:install) do
        bin.install "soulstream"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/impire-io/soulstream/releases/download/v0.14.0-rc.4/soulstream_0.14.0-rc.4_darwin_arm64.tar.gz"
      sha256 "019b2b8e3c08d641d84e79284384712b8de6cd0bd3c215e00e994c253cb12f35"

      define_method(:install) do
        bin.install "soulstream"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/impire-io/soulstream/releases/download/v0.14.0-rc.4/soulstream_0.14.0-rc.4_linux_amd64.tar.gz"
      sha256 "b8b8e700734c757a76f1eaef14ce7a1fe7d0f00d413176d8c9c16ed0a3214d66"
      define_method(:install) do
        bin.install "soulstream"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/impire-io/soulstream/releases/download/v0.14.0-rc.4/soulstream_0.14.0-rc.4_linux_arm64.tar.gz"
      sha256 "52e36f72fafc516bf68a266a102190990eec911c560bed93cc80ebbcfe1a00af"
      define_method(:install) do
        bin.install "soulstream"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/soulstream version")
  end
end
